### ISSUE TITLE
[BUG] 非校园网环境有timeout引发闪退（澡堂）

### ISSUE THREAD

**Issue by qhy040404** [qhy040404/Library-One-Tap-Android#29]
java.net.SocketTimeoutException: failed to connect to /202.118.74.5 (port 8193) from /10.30.27.167 (port 41012) after 10000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:236)
	at libcore.io.IoBridge.connect(IoBridge.java:180)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:621)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.qhy040404.libraryonetap.web.Requests.post(Requests.java:67)
	at com.qhy040404.libraryonetap.tools.BathReserveActivity$BathReserve.run(BathReserveActivity.kt:90)
	at java.lang.Thread.run(Thread.java:920)

澡堂必挂，这个更复杂

**Comment by qhy040404** [comment]
https://blog.csdn.net/TI_ZJW/article/details/114289681

**Comment by qhy040404** [comment]
https://www.jianshu.com/p/3910ee60ea07

**Comment by qhy040404** [comment]
“android.permission.ACCESS_COARSE_LOCATION”“android.permission.ACCESS_NETWORK_STATE”“android.permission.ACCESS_WIFI_STATE”“android.permission.CHANGE_NETWORK_STATE”“android.permission.CHANGE_WIFI_STATE”
